const countryData = [
  {
    country_name: "Afghanistan",
    acronym: "AF",
    total_holidays: 24,
    flag: "🇦🇫",
  },
  { country_name: "Albania", acronym: "AL", total_holidays: 33, flag: "🇦🇱" },
  { country_name: "Algeria", acronym: "DZ", total_holidays: 16, flag: "🇩🇿" },
  {
    country_name: "American Samoa",
    acronym: "AS",
    total_holidays: 17,
    flag: "🇦🇸",
  },
  { country_name: "Andorra", acronym: "AD", total_holidays: 28, flag: "🇦🇩" },
  { country_name: "Angola", acronym: "AO", total_holidays: 18, flag: "🇦🇴" },
  { country_name: "Anguilla", acronym: "AI", total_holidays: 19, flag: "🇦🇮" },
  {
    country_name: "Antigua and Barbuda",
    acronym: "AG",
    total_holidays: 15,
    flag: "🇦🇬",
  },
  { country_name: "Argentina", acronym: "AR", total_holidays: 41, flag: "🇦🇷" },
  { country_name: "Armenia", acronym: "AM", total_holidays: 37, flag: "🇦🇲" },
  { country_name: "Aruba", acronym: "AW", total_holidays: 15, flag: "🇦🇼" },
  { country_name: "Australia", acronym: "AU", total_holidays: 104, flag: "🇦🇺" },
  { country_name: "Austria", acronym: "AT", total_holidays: 36, flag: "🇦🇹" },
  { country_name: "Azerbaijan", acronym: "AZ", total_holidays: 33, flag: "🇦🇿" },
  { country_name: "Bahrain", acronym: "BH", total_holidays: 21, flag: "🇧🇭" },
  { country_name: "Bangladesh", acronym: "BD", total_holidays: 63, flag: "🇧🇩" },
  { country_name: "Barbados", acronym: "BB", total_holidays: 25, flag: "🇧🇧" },
  { country_name: "Belarus", acronym: "BY", total_holidays: 32, flag: "🇧🇾" },
  { country_name: "Belgium", acronym: "BE", total_holidays: 32, flag: "🇧🇪" },
  { country_name: "Belize", acronym: "BZ", total_holidays: 19, flag: "🇧🇿" },
  { country_name: "Benin", acronym: "BJ", total_holidays: 22, flag: "🇧🇯" },
  { country_name: "Bermuda", acronym: "BM", total_holidays: 23, flag: "🇧🇲" },
  { country_name: "Bhutan", acronym: "BT", total_holidays: 26, flag: "🇧🇹" },
  { country_name: "Bolivia", acronym: "BO", total_holidays: 24, flag: "🇧🇴" },
  {
    country_name: "Bosnia and Herzegovina",
    acronym: "BA",
    total_holidays: 38,
    flag: "🇧🇦",
  },
  { country_name: "Botswana", acronym: "BW", total_holidays: 21, flag: "🇧🇼" },
  { country_name: "Brazil", acronym: "BR", total_holidays: 29, flag: "🇧🇷" },
  {
    country_name: "British Virgin Islands",
    acronym: "VG",
    total_holidays: 19,
    flag: "🇻🇬",
  },
  { country_name: "Brunei", acronym: "BN", total_holidays: 23, flag: "🇧🇳" },
  { country_name: "Bulgaria", acronym: "BG", total_holidays: 28, flag: "🇧🇬" },
  {
    country_name: "Burkina Faso",
    acronym: "BF",
    total_holidays: 18,
    flag: "🇧🇫",
  },
  { country_name: "Burundi", acronym: "BI", total_holidays: 18, flag: "🇧🇮" },
  { country_name: "Cabo Verde", acronym: "CV", total_holidays: 15, flag: "🇨🇻" },
  { country_name: "Cambodia", acronym: "KH", total_holidays: 36, flag: "🇰🇭" },
  { country_name: "Cameroon", acronym: "CM", total_holidays: 18, flag: "🇨🇲" },
  { country_name: "Canada", acronym: "CA", total_holidays: 118, flag: "🇨🇦" },
  {
    country_name: "Cayman Islands",
    acronym: "KY",
    total_holidays: 24,
    flag: "🇰🇾",
  },
  {
    country_name: "Central African Republic",
    acronym: "CF",
    total_holidays: 18,
    flag: "🇨🇫",
  },
  { country_name: "Chad", acronym: "TD", total_holidays: 19, flag: "🇹🇩" },
  { country_name: "Chile", acronym: "CL", total_holidays: 23, flag: "🇨🇱" },
  { country_name: "China", acronym: "CN", total_holidays: 44, flag: "🇨🇳" },
  { country_name: "Colombia", acronym: "CO", total_holidays: 38, flag: "🇨🇴" },
  { country_name: "Comoros", acronym: "KM", total_holidays: 17, flag: "🇰🇲" },
  { country_name: "Congo", acronym: "CG", total_holidays: 17, flag: "🇨🇬" },
  {
    country_name: "Congo Democratic Republic",
    acronym: "CD",
    total_holidays: 22,
    flag: "🇨🇩",
  },
  {
    country_name: "Cook Islands",
    acronym: "CK",
    total_holidays: 16,
    flag: "🇨🇰",
  },
  { country_name: "Costa Rica", acronym: "CR", total_holidays: 23, flag: "🇨🇷" },
  {
    country_name: "Cote d'Ivoire",
    acronym: "CI",
    total_holidays: 18,
    flag: "🇨🇮",
  },
  { country_name: "Croatia", acronym: "HR", total_holidays: 23, flag: "🇭🇷" },
  { country_name: "Cuba", acronym: "CU", total_holidays: 22, flag: "🇨🇺" },
  { country_name: "Curaçao", acronym: "CW", total_holidays: 18, flag: "🇨🇼" },
  { country_name: "Cyprus", acronym: "CY", total_holidays: 26, flag: "🇨🇾" },
  { country_name: "Czechia", acronym: "CZ", total_holidays: 32, flag: "🇨🇿" },
  { country_name: "Denmark", acronym: "DK", total_holidays: 25, flag: "🇩🇰" },
  { country_name: "Djibouti", acronym: "DJ", total_holidays: 16, flag: "🇩🇯" },
  { country_name: "Dominica", acronym: "DM", total_holidays: 19, flag: "🇩🇲" },
  {
    country_name: "Dominican Republic",
    acronym: "DO",
    total_holidays: 21,
    flag: "🇩🇴",
  },
  { country_name: "East Timor", acronym: "TL", total_holidays: 19, flag: "🇹🇱" },
  { country_name: "Ecuador", acronym: "EC", total_holidays: 26, flag: "🇪🇨" },
  { country_name: "Egypt", acronym: "EG", total_holidays: 30, flag: "🇪🇬" },
  {
    country_name: "El Salvador",
    acronym: "SV",
    total_holidays: 29,
    flag: "🇸🇻",
  },
  {
    country_name: "Equatorial Guinea",
    acronym: "GQ",
    total_holidays: 19,
    flag: "🇬🇶",
  },
  { country_name: "Eritrea", acronym: "ER", total_holidays: 20, flag: "🇪🇷" },
  { country_name: "Estonia", acronym: "EE", total_holidays: 16, flag: "🇪🇪" },
  { country_name: "Ethiopia", acronym: "ET", total_holidays: 17, flag: "🇪🇹" },
  {
    country_name: "Falkland Islands",
    acronym: "FK",
    total_holidays: 17,
    flag: "🇫🇰",
  },
  {
    country_name: "Faroe Islands",
    acronym: "FO",
    total_holidays: 23,
    flag: "🇫🇴",
  },
  { country_name: "Fiji", acronym: "FJ", total_holidays: 16, flag: "🇫🇯" },
  { country_name: "Finland", acronym: "FI", total_holidays: 23, flag: "🇫🇮" },
  { country_name: "France", acronym: "FR", total_holidays: 25, flag: "🇫🇷" },
  {
    country_name: "French Polynesia",
    acronym: "PF",
    total_holidays: 17,
    flag: "🇵🇫",
  },
  { country_name: "Gabon", acronym: "GA", total_holidays: 19, flag: "🇬🇦" },
  { country_name: "Gambia", acronym: "GM", total_holidays: 19, flag: "🇬🇲" },
  { country_name: "Georgia", acronym: "GE", total_holidays: 25, flag: "🇬🇪" },
  { country_name: "Germany", acronym: "DE", total_holidays: 78, flag: "🇩🇪" },
  { country_name: "Ghana", acronym: "GH", total_holidays: 26, flag: "🇬🇭" },
  { country_name: "Gibraltar", acronym: "GI", total_holidays: 26, flag: "🇬🇮" },
  { country_name: "Greece", acronym: "GR", total_holidays: 24, flag: "🇬🇷" },
  { country_name: "Greenland", acronym: "GL", total_holidays: 21, flag: "🇬🇱" },
  { country_name: "Grenada", acronym: "GD", total_holidays: 20, flag: "🇬🇩" },
  { country_name: "Guam", acronym: "GU", total_holidays: 19, flag: "🇬🇺" },
  { country_name: "Guatemala", acronym: "GT", total_holidays: 25, flag: "🇬🇹" },
  { country_name: "Guernsey", acronym: "GG", total_holidays: 18, flag: "🇬🇬" },
  { country_name: "Guinea", acronym: "GN", total_holidays: 16, flag: "🇬🇳" },
  {
    country_name: "Guinea-Bissau",
    acronym: "GW",
    total_holidays: 13,
    flag: "🇬🇼",
  },
  { country_name: "Guyana", acronym: "GY", total_holidays: 23, flag: "🇬🇾" },
  { country_name: "Haiti", acronym: "HT", total_holidays: 23, flag: "🇭🇹" },
  { country_name: "Honduras", acronym: "HN", total_holidays: 24, flag: "🇭🇳" },
  { country_name: "Hong Kong", acronym: "HK", total_holidays: 30, flag: "🇭🇰" },
  { country_name: "Hungary", acronym: "HU", total_holidays: 26, flag: "🇭🇺" },
  { country_name: "Iceland", acronym: "IS", total_holidays: 28, flag: "🇮🇸" },
  { country_name: "India", acronym: "IN", total_holidays: 72, flag: "🇮🇳" },
  { country_name: "Indonesia", acronym: "ID", total_holidays: 35, flag: "🇮🇩" },
  { country_name: "Iran", acronym: "IR", total_holidays: 26, flag: "🇮🇷" },
  { country_name: "Iraq", acronym: "IQ", total_holidays: 25, flag: "🇮🇶" },
  { country_name: "Ireland", acronym: "IE", total_holidays: 17, flag: "🇮🇪" },
  {
    country_name: "Isle of Man",
    acronym: "IM",
    total_holidays: 16,
    flag: "🇮🇲",
  },
  { country_name: "Israel", acronym: "IL", total_holidays: 54, flag: "🇮🇱" },
  { country_name: "Italy", acronym: "IT", total_holidays: 24, flag: "🇮🇹" },
  { country_name: "Jamaica", acronym: "JM", total_holidays: 20, flag: "🇯🇲" },
  { country_name: "Japan", acronym: "JP", total_holidays: 36, flag: "🇯🇵" },
  { country_name: "Jersey", acronym: "JE", total_holidays: 15, flag: "🇯🇪" },
  { country_name: "Jordan", acronym: "JO", total_holidays: 29, flag: "🇯🇴" },
  { country_name: "Kazakhstan", acronym: "KZ", total_holidays: 26, flag: "🇰🇿" },
  { country_name: "Kenya", acronym: "KE", total_holidays: 22, flag: "🇰🇪" },
  { country_name: "Kiribati", acronym: "KI", total_holidays: 19, flag: "🇰🇮" },
  { country_name: "Kosovo", acronym: "XK", total_holidays: 30, flag: "🇽🇰" },
  { country_name: "Kuwait", acronym: "KW", total_holidays: 19, flag: "🇰🇼" },
  { country_name: "Kyrgyzstan", acronym: "KG", total_holidays: 22, flag: "🇰🇬" },
  { country_name: "Laos", acronym: "LA", total_holidays: 22, flag: "🇱🇦" },
  { country_name: "Latvia", acronym: "LV", total_holidays: 27, flag: "🇱🇻" },
  { country_name: "Lebanon", acronym: "LB", total_holidays: 36, flag: "🇱🇧" },
  { country_name: "Lesotho", acronym: "LS", total_holidays: 15, flag: "🇱🇸" },
  { country_name: "Liberia", acronym: "LR", total_holidays: 17, flag: "🇱🇷" },
  { country_name: "Libya", acronym: "LY", total_holidays: 18, flag: "🇱🇾" },
  {
    country_name: "Liechtenstein",
    acronym: "LI",
    total_holidays: 28,
    flag: "🇱🇮",
  },
  { country_name: "Lithuania", acronym: "LT", total_holidays: 27, flag: "🇱🇹" },
  { country_name: "Luxembourg", acronym: "LU", total_holidays: 20, flag: "🇱🇺" },
  { country_name: "Macau", acronym: "MO", total_holidays: 33, flag: "🇲🇴" },
  { country_name: "Madagascar", acronym: "MG", total_holidays: 18, flag: "🇲🇬" },
  { country_name: "Malawi", acronym: "MW", total_holidays: 19, flag: "🇲🇼" },
  { country_name: "Malaysia", acronym: "MY", total_holidays: 64, flag: "🇲🇾" },
  { country_name: "Maldives", acronym: "MV", total_holidays: 27, flag: "🇲🇻" },
  { country_name: "Mali", acronym: "ML", total_holidays: 17, flag: "🇲🇱" },
  { country_name: "Malta", acronym: "MT", total_holidays: 21, flag: "🇲🇹" },
  {
    country_name: "Marshall Islands",
    acronym: "MH",
    total_holidays: 17,
    flag: "🇲🇭",
  },
  { country_name: "Martinique", acronym: "MQ", total_holidays: 19, flag: "🇲🇶" },
  { country_name: "Mauritania", acronym: "MR", total_holidays: 12, flag: "🇲🇷" },
  { country_name: "Mauritius", acronym: "MU", total_holidays: 27, flag: "🇲🇺" },
  { country_name: "Mayotte", acronym: "YT", total_holidays: 19, flag: "🇾🇹" },
  { country_name: "Mexico", acronym: "MX", total_holidays: 45, flag: "🇲🇽" },
  { country_name: "Micronesia", acronym: "FM", total_holidays: 24, flag: "🇫🇲" },
  { country_name: "Moldova", acronym: "MD", total_holidays: 45, flag: "🇲🇩" },
  { country_name: "Monaco", acronym: "MC", total_holidays: 24, flag: "🇲🇨" },
  { country_name: "Mongolia", acronym: "MN", total_holidays: 31, flag: "🇲🇳" },
  { country_name: "Montenegro", acronym: "ME", total_holidays: 33, flag: "🇲🇪" },
  { country_name: "Montserrat", acronym: "MS", total_holidays: 16, flag: "🇲🇸" },
  { country_name: "Morocco", acronym: "MA", total_holidays: 23, flag: "🇲🇦" },
  { country_name: "Mozambique", acronym: "MZ", total_holidays: 16, flag: "🇲🇿" },
  { country_name: "Myanmar", acronym: "MM", total_holidays: 35, flag: "🇲🇲" },
  { country_name: "Namibia", acronym: "NA", total_holidays: 18, flag: "🇳🇦" },
  { country_name: "Nauru", acronym: "NR", total_holidays: 18, flag: "🇳🇷" },
  { country_name: "Nepal", acronym: "NP", total_holidays: 52, flag: "🇳🇵" },
  {
    country_name: "Netherlands",
    acronym: "NL",
    total_holidays: 21,
    flag: "🇳🇱",
  },
  {
    country_name: "New Caledonia",
    acronym: "NC",
    total_holidays: 17,
    flag: "🇳🇨",
  },
  {
    country_name: "New Zealand",
    acronym: "NZ",
    total_holidays: 38,
    flag: "🇳🇿",
  },
  { country_name: "Nicaragua", acronym: "NI", total_holidays: 22, flag: "🇳🇮" },
  { country_name: "Niger", acronym: "NE", total_holidays: 18, flag: "🇳🇪" },
  { country_name: "Nigeria", acronym: "NG", total_holidays: 36, flag: "🇳🇬" },
  {
    country_name: "North Korea",
    acronym: "KP",
    total_holidays: 21,
    flag: "🇰🇵",
  },
  {
    country_name: "North Macedonia",
    acronym: "MK",
    total_holidays: 46,
    flag: "🇲🇰",
  },
  {
    country_name: "Northern Mariana Islands",
    acronym: "MP",
    total_holidays: 20,
    flag: "🇲🇵",
  },
  { country_name: "Norway", acronym: "NO", total_holidays: 44, flag: "🇳🇴" },
  { country_name: "Oman", acronym: "OM", total_holidays: 22, flag: "🇴🇲" },
  { country_name: "Pakistan", acronym: "PK", total_holidays: 55, flag: "🇵🇰" },
  { country_name: "Palau", acronym: "PW", total_holidays: 17, flag: "🇵🇼" },
  { country_name: "Panama", acronym: "PA", total_holidays: 28, flag: "🇵🇦" },
  {
    country_name: "Papua New Guinea",
    acronym: "PG",
    total_holidays: 15,
    flag: "🇵🇬",
  },
  { country_name: "Paraguay", acronym: "PY", total_holidays: 20, flag: "🇵🇾" },
  { country_name: "Peru", acronym: "PE", total_holidays: 30, flag: "🇵🇪" },
  {
    country_name: "Philippines",
    acronym: "PH",
    total_holidays: 35,
    flag: "🇵🇭",
  },
  { country_name: "Poland", acronym: "PL", total_holidays: 25, flag: "🇵🇱" },
  { country_name: "Portugal", acronym: "PT", total_holidays: 41, flag: "🇵🇹" },
  {
    country_name: "Puerto Rico",
    acronym: "PR",
    total_holidays: 30,
    flag: "🇵🇷",
  },
  { country_name: "Qatar", acronym: "QA", total_holidays: 23, flag: "🇶🇦" },
  { country_name: "Reunion", acronym: "RE", total_holidays: 16, flag: "🇷🇪" },
  { country_name: "Romania", acronym: "RO", total_holidays: 35, flag: "🇷🇴" },
  { country_name: "Russia", acronym: "RU", total_holidays: 31, flag: "🇷🇺" },
  { country_name: "Rwanda", acronym: "RW", total_holidays: 17, flag: "🇷🇼" },
  {
    country_name: "Saint Helena",
    acronym: "SH",
    total_holidays: 14,
    flag: "🇸🇭",
  },
  {
    country_name: "Saint Kitts and Nevis",
    acronym: "KN",
    total_holidays: 16,
    flag: "🇰🇳",
  },
  {
    country_name: "Saint Lucia",
    acronym: "LC",
    total_holidays: 17,
    flag: "🇱🇨",
  },
  {
    country_name: "Saint Martin",
    acronym: "MF",
    total_holidays: 19,
    flag: "🇲🇫",
  },
  {
    country_name: "Saint Pierre and Miquelon",
    acronym: "PM",
    total_holidays: 17,
    flag: "🇵🇲",
  },
  {
    country_name: "Saint Vincent and the Grenadines",
    acronym: "VC",
    total_holidays: 16,
    flag: "🇻🇨",
  },
  { country_name: "Samoa", acronym: "WS", total_holidays: 17, flag: "🇼🇸" },
  { country_name: "San Marino", acronym: "SM", total_holidays: 28, flag: "🇸🇲" },
  {
    country_name: "Sao Tome and Principe",
    acronym: "ST",
    total_holidays: 12,
    flag: "🇸🇹",
  },
  {
    country_name: "Saudi Arabia",
    acronym: "SA",
    total_holidays: 16,
    flag: "🇸🇦",
  },
  { country_name: "Senegal", acronym: "SN", total_holidays: 20, flag: "🇸🇳" },
  { country_name: "Serbia", acronym: "RS", total_holidays: 23, flag: "🇷🇸" },
  { country_name: "Seychelles", acronym: "SC", total_holidays: 19, flag: "🇸🇨" },
  {
    country_name: "Sierra Leone",
    acronym: "SL",
    total_holidays: 15,
    flag: "🇸🇱",
  },
  { country_name: "Singapore", acronym: "SG", total_holidays: 33, flag: "🇸🇬" },
  {
    country_name: "Sint Maarten",
    acronym: "SX",
    total_holidays: 18,
    flag: "🇸🇽",
  },
  { country_name: "Slovakia", acronym: "SK", total_holidays: 36, flag: "🇸🇰" },
  { country_name: "Slovenia", acronym: "SI", total_holidays: 23, flag: "🇸🇮" },
  {
    country_name: "Solomon Islands",
    acronym: "SB",
    total_holidays: 31,
    flag: "🇸🇧",
  },
  { country_name: "Somalia", acronym: "SO", total_holidays: 16, flag: "🇸🇴" },
  {
    country_name: "South Africa",
    acronym: "ZA",
    total_holidays: 41,
    flag: "🇿🇦",
  },
  {
    country_name: "South Korea",
    acronym: "KR",
    total_holidays: 31,
    flag: "🇰🇷",
  },
  {
    country_name: "South Sudan",
    acronym: "SS",
    total_holidays: 21,
    flag: "🇸🇸",
  },
  { country_name: "Spain", acronym: "ES", total_holidays: 70, flag: "🇪🇸" },
  { country_name: "Sri Lanka", acronym: "LK", total_holidays: 42, flag: "🇱🇰" },
  { country_name: "St. Barts", acronym: "BL", total_holidays: 22, flag: "🇧🇱" },
  { country_name: "Sudan", acronym: "SD", total_holidays: 19, flag: "🇸🇩" },
  { country_name: "Suriname", acronym: "SR", total_holidays: 20, flag: "🇸🇷" },
  { country_name: "Sweden", acronym: "SE", total_holidays: 34, flag: "🇸🇪" },
  {
    country_name: "Switzerland",
    acronym: "CH",
    total_holidays: 41,
    flag: "🇨🇭",
  },
  { country_name: "Syria", acronym: "SY", total_holidays: 21, flag: "🇸🇾" },
  { country_name: "Taiwan", acronym: "TW", total_holidays: 51, flag: "🇹🇼" },
  { country_name: "Tajikistan", acronym: "TJ", total_holidays: 17, flag: "🇹🇯" },
  { country_name: "Tanzania", acronym: "TZ", total_holidays: 23, flag: "🇹🇿" },
  { country_name: "Thailand", acronym: "TH", total_holidays: 43, flag: "🇹🇭" },
  {
    country_name: "The Bahamas",
    acronym: "BS",
    total_holidays: 24,
    flag: "🇧🇸",
  },
  { country_name: "Togo", acronym: "TG", total_holidays: 19, flag: "🇹🇬" },
  { country_name: "Tonga", acronym: "TO", total_holidays: 19, flag: "🇹🇴" },
  {
    country_name: "Trinidad and Tobago",
    acronym: "TT",
    total_holidays: 27,
    flag: "🇹🇹",
  },
  { country_name: "Tunisia", acronym: "TN", total_holidays: 19, flag: "🇹🇳" },
  { country_name: "Turkey", acronym: "TR", total_holidays: 24, flag: "🇹🇷" },
  {
    country_name: "Turkmenistan",
    acronym: "TM",
    total_holidays: 23,
    flag: "🇹🇲",
  },
  {
    country_name: "Turks and Caicos Islands",
    acronym: "TC",
    total_holidays: 18,
    flag: "🇹🇨",
  },
  { country_name: "Tuvalu", acronym: "TV", total_holidays: 17, flag: "🇹🇻" },
  {
    country_name: "US Virgin Islands",
    acronym: "VI",
    total_holidays: 29,
    flag: "🇻🇮",
  },
  { country_name: "Uganda", acronym: "UG", total_holidays: 21, flag: "🇺🇬" },
  { country_name: "Ukraine", acronym: "UA", total_holidays: 37, flag: "🇺🇦" },
  {
    country_name: "United Arab Emirates",
    acronym: "AE",
    total_holidays: 23,
    flag: "🇦🇪",
  },
  {
    country_name: "United Kingdom",
    acronym: "GB",
    total_holidays: 95,
    flag: "🇬🇧",
  },
  {
    country_name: "United States",
    acronym: "US",
    total_holidays: 418,
    flag: "🇺🇸",
  },
  { country_name: "Uruguay", acronym: "UY", total_holidays: 25, flag: "🇺🇾" },
  { country_name: "Uzbekistan", acronym: "UZ", total_holidays: 14, flag: "🇺🇿" },
  { country_name: "Vanuatu", acronym: "VU", total_holidays: 18, flag: "🇻🇺" },
  {
    country_name: "Vatican City (Holy See)",
    acronym: "VA",
    total_holidays: 29,
    flag: "🇻🇦",
  },
  { country_name: "Venezuela", acronym: "VE", total_holidays: 42, flag: "🇻🇪" },
  { country_name: "Vietnam", acronym: "VN", total_holidays: 32, flag: "🇻🇳" },
  {
    country_name: "Wallis and Futuna",
    acronym: "WF",
    total_holidays: 16,
    flag: "🇼🇫",
  },
  { country_name: "Yemen", acronym: "YE", total_holidays: 22, flag: "🇾🇪" },
  { country_name: "Zambia", acronym: "ZM", total_holidays: 22, flag: "🇿🇲" },
  { country_name: "Zimbabwe", acronym: "ZW", total_holidays: 22, flag: "🇿🇼" },
  { country_name: "eSwatini", acronym: "SZ", total_holidays: 17, flag: "🇸🇿" },
];

export default countryData;
